### ISSUE TITLE
用在我的vue项目中样式有出入，我整个项目的最大宽度是750，求大神帮忙

### ISSUE THREAD

**Issue by zhengyanghuaer** [landluck/lucky_wheel#1]
![image](https://user-images.githubusercontent.com/35128870/41326753-1dc784e0-6ef3-11e8-9803-a353a4c008fb.png)

**Comment by landluck** [comment]
你检查一下css吧，这是css的问题

**Comment by treeeeee** [comment]
转盘转的角度与 实际 获奖不匹配
![image](https://user-images.githubusercontent.com/30005909/45076940-636ca580-b11e-11e8-8f35-e1c32752e573.png)
![image](https://user-images.githubusercontent.com/30005909/45076945-6a93b380-b11e-11e8-9d99-6602e5f6e29d.png)

**Comment by lurongyao** [comment]
我跑了下项目也是的，箭头转到未中奖时，弹框显示中奖了

**Comment by 54dujianchao** [comment]
不知道 这个代码 咋用啊，我是做服务器开发的，有直接能打开的源码么
