### ISSUE TITLE
能调整个数么

### ISSUE THREAD

**Issue by 54dujianchao** [landluck/lucky_wheel#3]
我想把奖品数量 改为自定义数量，比如2-10个

**Comment by f056917** [comment]
同问，后台需要运营手动添加奖品数量，现在是写死的8个，就很尴尬

**Comment by zhouseahe** [comment]
我这边调整为6个，
js 
 var result_angle = [330, 270, 210, 150, 90, 30]; //最终会旋转到下标的位置所需要的度数
css
.prize-list .prize-item:first-child {
  top: 0;
  left: 8.8rem;
  transform: rotate(30deg);
}
.prize-list .prize-item:nth-child(2) {
  top: 4.6rem;
  left: 11.4rem;
  transform: rotate(90deg);
}
.prize-list .prize-item:nth-child(3) {
  top: 9.2rem;
  left: 9rem;
  transform: rotate(150deg);
}
.prize-list .prize-item:nth-child(4) {
  top: 9rem;
  left: 3.8rem;
  transform: rotate(210deg);
}
.prize-list .prize-item:nth-child(5) {
  top: 4.7rem;
  left: 1.3rem;
  transform: rotate(270deg);
}
.prize-list .prize-item:nth-child(6) {
  top: 0.2rem;
  left: 3.8rem;
  transform: rotate(330deg);
}

**Comment by f056917** [comment]
@zhouseahe 这样每次都要修改前端代码，不太合适

**Comment by landluck** [comment]
重新修改了实现，可以看下，奖项是根据列表动态渲染的，不过需要自行更换转盘背景图
